version: "3.2"
services:
  elasticsearch:
    build: ./elasticsearch/ 
    container_name: elasticsearch
    volumes: 
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

  kibana:
    build: ./kibana/ 
    container_name: kibana
    volumes: 
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

        # logstash:
        #   build: ./logstash/ 
        #   container_name: logstash
        #   volumes: 
        #     - type: bind
        #       source: ./logstash/config/logstash.yml
        #       target: /usr/share/logstash/config/logstash.yml
        #       read_only: true
        #     - type: bind
        #       source: ./logstash/pipeline
        #       target: /usr/share/logstash/pipeline
        #       read_only: true
        #   ports:
        #     - "5044:5044"
        #     - "5000:5000/tcp"
        #     - "5000:5000/udp"
        #     - "9600:9600"
        #   networks:
        #     - elk
        #   depends_on:
        #     - elasticsearch

networks:
  elk:
    driver: bridge


